version: "3.1"

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: changeMe
        volumes:
            - mysql-data:/var/lib/mysql
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

    suitecrm:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80
        volumes: 
            - ./:/var/www/html/
        depends_on:
            - db

volumes:
    mysql-data: